version: '3.8'
services:
  tensorman:
    build:
      context: ./tensorman
      dockerfile: Dockerfile
    ports:
      - "8989:8888"
    volumes:
      - ./tensorman:/app
      - shared-data:/shared
    restart: always
  app:
    build: .
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - shared-data:/shared


volumes:
  shared-data:

